### ISSUE TITLE
Sound from Harmony doesn't match Google Play Music

### ISSUE THREAD

**Issue by jc00ke** [vincelwt/harmony#129]
It's hard to describe, but the sound coming from Harmony is a slight bit slow and doesn't have the bass or treble that the web version of GPM has.

The Weeknd's "Cant' Feel My Face" is a good example.

Not sure how I can help debug, but I'm game.

**Comment by vincelwt** [comment]
Hi,
I'll make some tests, do you have this problem with every tracks or only a few ?

**Comment by jc00ke** [comment]
I've tested with a number of songs and "Can't Feel My Face" is the worst among them. The others, take Kid Cuddi's "Just What I Am" sounds much more full on Google Play Music than it does in Harmony.

**Comment by vincelwt** [comment]
Ok I believe I fixed the bug. The problem was that the user wasn't logged in to Google until the library was refreshed, so as a workaround Harmony would play tracks from YouTube.
It should be working fine with next release, coming in a few days.

Until then as a workaround you can refresh your library before playing tracks or simply enable refreshing of the library at start in the settings.

**Comment by vincelwt** [comment]
Fixed with v0.6.0, could you confirm?

**Comment by jc00ke** [comment]
Confirmed, sounds good!
