### ISSUE TITLE
Google Music not playing correct songs

### ISSUE THREAD

**Issue by CharlesAngerstein** [vincelwt/harmony#171]
I have a paid Google Music subscription.  Harmony lists my collection of songs but it seems like some of the songs are being switched out for mixes of the same song.  Two examples are We Don't Talk Anymore by Charlie Puth and Closer, by the Chainsmokers.  I've checked on the web interface and the songs are quite different than the ones Harmony is playing.

**Comment by vincelwt** [comment]
Hi!
I recently fixed this bug, the problem was that the user wasn't logged in to Google until the library was refreshed, so as a workaround Harmony would play tracks from YouTube. 
It should be working fine with next release, coming in a few days.

Until then as a workaround you can refresh your library before playing tracks or simply enable refreshing of the library at start in the settings.

**Comment by CharlesAngerstein** [comment]
Thank you.
