### ISSUE TITLE
Empty KDE Media Player widget

### ISSUE THREAD

**Issue by pasteley** [vincelwt/harmony#176]
ArchLinux 4.11.9-1-ARCH 
KDE 5.35.0 / Plasma 5.10.3
Harmony 0.6.0-x64 installed from aur and executed as appimage (for testing)

![kde media widget](https://user-images.githubusercontent.com/1609081/27996305-e97030e0-64e7-11e7-9ef4-8665ba5dfa41.png)

Media Player Controls Widget stays empty and I am getting message to terminal pressing play button: `mprisPlayer enabled false`

```
app.js:30 We are on a -linux- system
utils.js:45 Checking for updates...
utils.js:54 Latest release is v0.6.0 and we're running 0.6.0
player.js:128 Uncaught (in promise) DOMException: The element has no supported sources.
playPause @ player.js:128
onclick @ index.html:25
```

Despite this, notifications works well.
Didn't had this problem on OpenSUSE Tumbleweed KDE with rpm installation

Thank you for your work!

**Comment by vincelwt** [comment]
Hi!
Sorry for the late answer.

It seems like Harmony doesn't detect that MPRIS (the media widget protocol) is available. I suspect this is due to the installation/running method.

Did you integrate, when asked on the first start, Harmony to your system (so it can be present in the menus) ? Without that, Harmony cannot use the MPRIS. You can check in your app menus if Harmony is present.
