### ISSUE TITLE
Add instant radio/themed radio for Google Play

### ISSUE THREAD

**Issue by acqcolor** [vincelwt/harmony#29]
Right now, it looks like you can only play playlists and individual songs from Google play

**Comment by w0xel** [comment]
Currently, if you request the "I'm feeling lucky" station from google play via commandline,  you always get the same instead of remixing it like google does it in their official player. The python project gmusicapi also has this problem...

My Idea would be implementing this service by creating a station randomly from your "thumbs up" playlist, also randomizing the type of the station (from track, album, genre, artist).

Would this be an acceptable workaround until someone finds out how to reset I'm feeling lucky via api?


Also: How to manage other stations? Loading all recent stations from the account would clutter the player immensely. How about adding a submenu to the rightclick menu in a google play playlist in harmony createStationFrom => { title, album, genre, artist } and only having one custom station present in the UI at a time?

@vincelwt is it currently possible to create custom rightclickmenus for services?

**Comment by vincelwt** [comment]
@w0xel At the end of each plugin js file there is a service.contextmenuItems array where you can add right click items. 

As it is based on [this plugin](https://github.com/electerious/basicContext), you can't for now add submenus, but only direct clickable items, which will connect to functions where you can access the track metadatas.

**Comment by vincelwt** [comment]
Thanks to @w0xel, I think we can close this, as it is now possible to create track based stations with All-access tracks.
