### ISSUE TITLE
No load all songs from big spotify list

### ISSUE THREAD

**Issue by elesdoar** [vincelwt/harmony#94]
Not load all songs from my spotify list, This has more than 2000 songs.

![Spotify List](https://cloud.githubusercontent.com/assets/3817595/19817175/07f32cfc-9d10-11e6-916c-aff50d042908.png)

I'm premium user.

**Comment by vincelwt** [comment]
Hi,
Could you tell how many tracks are showing for the playlist ? 200 ?

Is this the playlist of the tracks you liked/added (by pressing + for example ?) or is this a playlist you created ?

Because playlists are currently limited to 200 tracks (I'm working on that) but liked tracks should show everything

**Comment by elesdoar** [comment]
Hi,

It is a list created by me.

**Comment by vincelwt** [comment]
Ok then it's normal, I'll try correcting it soon.

**Comment by vincelwt** [comment]
Will be available in next release :)
